apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector: # replica set labels
    matchLabels:
      app: nginx
      tier: frontend
  template: # pod definition
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: nginx
        # image: nginx this is for the previous version
        image: nginx:mainline-alpine3.20-perl # Now to updated for the new version.
