apiVersion: v1
kind: Pod
metadata:
  name: label-demo
  labels:
    name: Jashwanth
    role: "DevOpsEngineer"
spec:
# list of containers
  containers:
  - name: hello-pod
    image: nginx
    ports:
    - containerPort: 80