apiVersion: v1
kind: Pod
metadata:
  name: resources-pod
  namespace: mechanoidstore
spec:
  # list of containers
  containers:
  - name: resources-pod
    image: nginx
    # port will not open just for information
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "100m"
        memory: "68Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"