apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
# list of containers
  containers:
  - name: secret-pod
    image: nginx
# list of containers
    ports:
    - containerPort: 80
    envFrom:
    - secretRef:
        name: devops-secret